"""Card-action token minting and atomic claim logic (Task 9).

Token scheme
------------
Each token is a URL-safe base64-encoded 20-byte (160-bit) random value
generated by ``secrets.token_urlsafe(20)``.  This gives ≥128 bits of
entropy and is globally unguessable without any HMAC layer.  The
source-message-ref comparison (all four fields) provides the
anti-spoofing gate: even a stolen token cannot be redeemed from a
different chat/message.

Idempotency
-----------
``mint_card_action`` uses SQLAlchemy Core ``INSERT … ON CONFLICT DO NOTHING``
so two concurrent callers with the same logical key both succeed at the
Python level, but only one row is inserted; the loser re-queries and
returns the winner's token.

Atomic claim
------------
``verify_and_claim`` issues a single ``UPDATE … WHERE status='pending'``
guarded UPDATE; only the session whose UPDATE affects 1 row "wins".
"""
from __future__ import annotations

import enum
import secrets
from datetime import datetime, timedelta
from typing import Union

from sqlalchemy import select, update
from sqlalchemy.dialects.sqlite import insert as sqlite_insert
from sqlalchemy.orm import Session

from app.models import GatewayBinding, GatewayCardAction
from app.services.gateway.types import MessageRef


# ---------------------------------------------------------------------------
# Typed errors
# ---------------------------------------------------------------------------

class ClaimError(enum.Enum):
    """Typed error variants returned by ``verify_and_claim``."""
    bad_token = "bad_token"
    expired = "expired"
    source_mismatch = "source_mismatch"
    already_resolved = "already_resolved"


# ---------------------------------------------------------------------------
# Minting
# ---------------------------------------------------------------------------

def mint_card_action(
    session: Session,
    *,
    binding: GatewayBinding,
    thread_id: int,
    message_id: int,
    action_id: str,
    decision: str,
    out_ref: MessageRef,
    settings,
) -> str:
    """Mint (or retrieve existing) card-action token for a logical action key.

    Returns the token string.  The operation is IDEMPOTENT: if a row already
    exists for ``(thread_id, message_id, action_id, decision)`` the existing
    token is returned and no second row is created.
    """
    ttl_s: int = settings.gateway_card_action_ttl_s
    expires_at = datetime.utcnow() + timedelta(seconds=ttl_s)
    new_token = secrets.token_urlsafe(20)  # 160 bits → ≥128-bit

    # INSERT … ON CONFLICT(thread_id, message_id, action_id, decision) DO NOTHING
    # We use SQLite dialect insert; for portability we fall back gracefully.
    stmt = (
        sqlite_insert(GatewayCardAction)
        .values(
            token=new_token,
            out_connector=out_ref.connector,
            out_workspace_id=out_ref.workspace_id,
            out_chat_id=out_ref.chat_id,
            out_message_id=out_ref.message_id,
            binding_id=binding.id,
            thread_id=thread_id,
            message_id=message_id,
            action_id=action_id,
            decision=decision,
            expires_at=expires_at,
            status="pending",
        )
        .on_conflict_do_nothing(index_elements=["thread_id", "message_id", "action_id", "decision"])
    )
    session.execute(stmt)
    session.flush()

    # Retrieve the authoritative token (new or pre-existing).
    row = session.execute(
        select(GatewayCardAction).where(
            GatewayCardAction.thread_id == thread_id,
            GatewayCardAction.message_id == message_id,
            GatewayCardAction.action_id == action_id,
            GatewayCardAction.decision == decision,
        )
    ).scalar_one()
    return row.token


# ---------------------------------------------------------------------------
# Verification & atomic claim
# ---------------------------------------------------------------------------

def verify_and_claim(
    session: Session,
    *,
    token: str,
    source_message_ref: MessageRef,
) -> Union[GatewayCardAction, ClaimError]:
    """Verify token and atomically claim it.

    Steps:
    1. Look up the token — ``bad_token`` if not found.
    2. Check expiry — ``expired`` if past ``expires_at``.
    3. Validate ALL four source fields against the stored out_* columns —
       ``source_mismatch`` if any field differs.
    4. Atomic claim via ``UPDATE … WHERE status='pending'`` — ``already_resolved``
       if claim is lost (status was not pending or another worker won the race).

    Returns the updated ``GatewayCardAction`` row on success.
    """
    # Step 1 — existence
    row = session.execute(
        select(GatewayCardAction).where(GatewayCardAction.token == token)
    ).scalar_one_or_none()

    if row is None:
        return ClaimError.bad_token

    # Step 2 — expiry
    if datetime.utcnow() >= row.expires_at:
        return ClaimError.expired

    # Step 3 — source match (ALL four fields)
    if (
        row.out_connector != source_message_ref.connector
        or row.out_workspace_id != source_message_ref.workspace_id
        or row.out_chat_id != source_message_ref.chat_id
        or row.out_message_id != source_message_ref.message_id
    ):
        return ClaimError.source_mismatch

    # Step 4 — atomic claim: UPDATE only if status == 'pending'
    result = session.execute(
        update(GatewayCardAction)
        .where(GatewayCardAction.token == token, GatewayCardAction.status == "pending")
        .values(status="resolving")
    )
    session.flush()

    if result.rowcount != 1:
        return ClaimError.already_resolved

    # Refresh in-memory state after the UPDATE
    session.refresh(row)
    return row


# ---------------------------------------------------------------------------
# Status transitions
# ---------------------------------------------------------------------------

def mark_resolved(
    session: Session,
    row: GatewayCardAction,
    *,
    resolved_by_binding_id: int | None = None,
) -> None:
    """Transition a resolving action to resolved."""
    row.status = "resolved"
    row.resolved_by_binding_id = resolved_by_binding_id
    session.flush()


def mark_failed(session: Session, row: GatewayCardAction) -> None:
    """Transition a resolving action to failed."""
    row.status = "failed"
    session.flush()


def mark_unknown(session: Session, row: GatewayCardAction) -> None:
    """Transition a resolving action to unknown (outcome uncertain)."""
    row.status = "unknown"
    session.flush()
