#!/usr/bin/env python
"""Emit a run's board tables and chart sidecar straight from the arena DB.

Report prose is written by a human; the numbers are not. This mirrors the report
module's split — deterministic blocks resolve the figures, narrative wraps them —
so no score reaches a published markdown table by hand-transcription.

Writes `<out>.tables.md` and `<out>.charts.json` (the sidecar
`docs/arena/render_report.py` reads).

Example:
    python scripts/arena_board_tables.py --run-id 104 \
        --out docs/arena/2026-08-13-run104-otc-desk-agent-arena
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

STAT_ORDER = ("GRD", "ADH", "SYN", "EFF", "PRC", "CON")
WORKFLOW_SHORT = {
    "risk-manager-control-day": "Risk Control",
    "trader-rfq-booking-day": "Trader RFQ",
    "high-board-portfolio-review-day": "Portfolio Review",
    "risk-limit-breach-day": "Limit Breach",
    "ops-settlement-day": "Ops Settlement",
}


def _cell(value) -> str:
    return "—" if value is None else str(value)


def _effort(value) -> str:
    """Render a contestant's pinned effort, or an em dash when unpinned.

    `None` is an ABSENCE, not a level, so it must not render as a word that
    looks like one. Every surface showing a contestant has to show this: a
    board can carry the same model at two efforts (they are separate
    contestants), and without the column they are indistinguishable rows --
    same model, same workflow, same status, same radar. Run #109 shipped
    exactly that, Grok 4.6 twice at OVR 75 and 74 with no way to tell which
    arm was which.
    """
    return "—" if value in (None, "") else str(value)


def _mean_tool_calls(bd: dict) -> float | None:
    """Mean counted tool calls across trials.

    ``aggregate`` is a LIST of per-trial breakdowns, one entry per trial — not a
    single dict. A single-trial row falls back to the top-level diagnosis.
    """
    trials = bd.get("aggregate")
    if isinstance(trials, list) and trials:
        counts = [t.get("diagnosis", {}).get("counts_detail", {}).get("tool_calls")
                  for t in trials]
        counts = [c for c in counts if isinstance(c, (int, float))]
        if counts:
            return sum(counts) / len(counts)
    top = bd.get("diagnosis", {}).get("counts_detail", {}).get("tool_calls")
    return top if isinstance(top, (int, float)) else None


def build(run_id: int) -> tuple[str, list]:
    from app.database import SessionLocal
    from app.services.arena import store
    from app.services.arena.models import get_model

    session = SessionLocal()
    try:
        run = store.get_run(session, run_id)
        if run is None:
            raise SystemExit(f"run {run_id} not found")
        board = store.leaderboard(session, run_id=run_id)

        lines: list[str] = []
        lines.append(f"<!-- generated by scripts/arena_board_tables.py from run {run_id} -->")
        lines.append("")
        lines.append("### Hero cards — mean across all scored workflows")
        lines.append("")
        lines.append("| Model | Eff | OVR | " + " | ".join(STAT_ORDER)
                     + " | Obj | Workflows |")
        lines.append("|---|:---:|:---:|" + ":---:|" * len(STAT_ORDER) + ":---:|:---:|")
        for row in board:
            mean = row.get("card_mean")
            name = get_model(row["model_id"]).display_name
            eff = _effort(row.get("reasoning_effort"))
            if not mean:
                lines.append(f"| {name} | {eff} | — | "
                             + " | ".join("—" for _ in STAT_ORDER)
                             + f" | {row.get('mean_objective')} | "
                             f"{row.get('carded_count')}/{row.get('match_count')} uncarded |")
                continue
            # `con` is present-but-None on a single-trial row (no dispersion to
            # measure), so a .get() default never fires — coalesce explicitly.
            stats = [_cell(mean.get("con" if s == "CON" else s)) for s in STAT_ORDER]
            obj = row.get("mean_objective")
            lines.append(f"| **{name}** | {eff} | **{mean['ovr']}** | "
                         + " | ".join(stats)
                         + f" | {obj:.1f} | {row.get('match_count')} |")
        lines.append("")

        lines.append("### Per-workflow cards")
        lines.append("")
        lines.append("| Model | Eff | Workflow | OVR | " + " | ".join(STAT_ORDER)
                     + " | Obj | Trials | Calls |")
        lines.append("|---|:---:|---|:---:|" + ":---:|" * len(STAT_ORDER)
                     + ":---:|:---:|:---:|")
        for m in sorted(run["matches"],
                        key=lambda x: (x["model_id"], x.get("reasoning_effort") or "",
                                       x["workflow_id"])):
            bd = m.get("score_breakdown") or {}
            card = bd.get("card")
            name = get_model(m["model_id"]).display_name
            eff = _effort(m.get("reasoning_effort"))
            wf = WORKFLOW_SHORT.get(m["workflow_id"], m["workflow_id"])
            if m["status"] != "scored":
                lines.append(f"| {name} | {eff} | {wf} | — | "
                             + " | ".join("—" for _ in STAT_ORDER)
                             + f" | — | — | {m['status']}: {m.get('error') or ''} |")
                continue
            calls = _mean_tool_calls(bd)
            if card:
                vals = [_cell(card.get("con") if s == "CON" else card["stats"].get(s))
                        for s in STAT_ORDER]
                ovr = str(card["ovr"])
            else:
                vals = ["—"] * len(STAT_ORDER)
                ovr = f"uncarded ({bd.get('card_reason')})"
            lines.append(f"| {name} | {eff} | {wf} | {ovr} | " + " | ".join(vals)
                         + f" | {m['objective_score']:.1f} | {bd.get('n_trials','—')} "
                         f"| {f'{calls:.0f}' if calls is not None else '—'} |")
        lines.append("")

        # Chart sidecar: [caption, axis_max, unit, rows], rows = [label, value, cls, vlabel]
        classes = ["gold", "silver", "bronze", "mid", "mid", "mid"]
        ovr_rows = []
        for i, row in enumerate(board):
            mean = row.get("card_mean")
            if not mean:
                continue
            name = get_model(row["model_id"]).display_name
            ovr_rows.append([name, mean["ovr"], classes[min(i, len(classes) - 1)],
                             str(mean["ovr"])])
        charts = [["Model Ability Card — OVR", 99, "", ovr_rows]]

        for stat in ("GRD", "EFF", "CON"):
            rows = []
            for i, row in enumerate(board):
                mean = row.get("card_mean")
                if not mean:
                    continue
                value = mean.get("con") if stat == "CON" else mean.get(stat)
                if value is None:
                    continue
                name = get_model(row["model_id"]).display_name
                rows.append([name, value, classes[min(i, len(classes) - 1)], str(value)])
            if rows:
                charts.append([f"{stat}", 99, "", rows])

        return "\n".join(lines), charts
    finally:
        session.close()


def _model_means(session, run_id: int) -> dict:
    """Per-model aggregates for one run: card stats, objective, mean calls, effort."""
    from app.services.arena import store

    run = store.get_run(session, run_id)
    if run is None:
        raise SystemExit(f"run {run_id} not found")
    board = {r["model_id"]: r for r in store.leaderboard(session, run_id=run_id)}

    calls: dict[str, list[float]] = {}
    per_wf: dict[tuple[str, str], dict] = {}
    for m in run["matches"]:
        if m["status"] != "scored":
            continue
        bd = m.get("score_breakdown") or {}
        c = _mean_tool_calls(bd)
        if c is not None:
            calls.setdefault(m["model_id"], []).append(c)
        per_wf[(m["model_id"], m["workflow_id"])] = {
            "ovr": (bd.get("card") or {}).get("ovr"),
            "obj": m["objective_score"],
            "calls": c,
        }

    out = {}
    for model_id, row in board.items():
        cs = calls.get(model_id) or []
        out[model_id] = {
            "row": row,
            "effort": row.get("reasoning_effort"),
            "calls": (sum(cs) / len(cs)) if cs else None,
        }
    return {"models": out, "per_wf": per_wf, "workflows": run["workflow_ids"]}


def _delta(a, b) -> str:
    """Signed delta cell, blank when either side is missing."""
    if a is None or b is None:
        return "—"
    d = a - b
    return f"{d:+.1f}" if isinstance(d, float) and abs(d) % 1 else f"{d:+.0f}"


def build_compare(run_id: int, baseline_run_id: int) -> str:
    """Paired within-model comparison of two runs (delta = run_id - baseline).

    The point of pairing: two boards at two efforts are two operating REGIMES,
    never one averaged row, and each model's own baseline arm is the only fair
    control for its treatment arm. A cross-board ranking comparison would
    confound the effort change with every difference between the fields.
    """
    from app.database import SessionLocal
    from app.services.arena.models import get_model

    session = SessionLocal()
    try:
        cur = _model_means(session, run_id)
        base = _model_means(session, baseline_run_id)

        lines: list[str] = []
        lines.append(f"<!-- generated by scripts/arena_board_tables.py "
                     f"--run-id {run_id} --baseline-run {baseline_run_id} -->")
        lines.append("")
        lines.append(f"### Paired effort comparison — run {run_id} vs run "
                     f"{baseline_run_id} (delta = run {run_id} minus baseline)")
        lines.append("")
        lines.append("| Model | Eff | OVR | " + " | ".join(STAT_ORDER)
                     + " | Obj | Calls |")
        lines.append("|---|:---:|:---:|" + ":---:|" * len(STAT_ORDER) + ":---:|:---:|")

        shared = [m for m in base["models"] if m in cur["models"]]
        shared.sort(key=lambda m: -((cur["models"][m]["row"].get("card_mean")
                                     or {}).get("ovr") or 0))

        for model_id in shared:
            name = get_model(model_id).display_name
            for tag, side in (("base", base), ("cur", cur)):
                e = side["models"][model_id]
                mean = e["row"].get("card_mean") or {}
                stats = [_cell(mean.get("con" if s == "CON" else s))
                         for s in STAT_ORDER]
                label = f"**{name}**" if tag == "base" else ""
                obj = e["row"].get("mean_objective")
                ncalls = "—" if e["calls"] is None else format(e["calls"], ".0f")
                lines.append(
                    f"| {label} | {_effort(e['effort'])} | "
                    f"{_cell(mean.get('ovr'))} | " + " | ".join(stats)
                    + f" | {obj:.1f} | {ncalls} |")
            bm = base["models"][model_id]["row"].get("card_mean") or {}
            cm = cur["models"][model_id]["row"].get("card_mean") or {}
            dstats = [_delta(cm.get("con" if s == "CON" else s),
                             bm.get("con" if s == "CON" else s))
                      for s in STAT_ORDER]
            lines.append(
                f"| | **Δ** | **{_delta(cm.get('ovr'), bm.get('ovr'))}** | "
                + " | ".join(dstats)
                + f" | {_delta(cur['models'][model_id]['row'].get('mean_objective'), base['models'][model_id]['row'].get('mean_objective'))} | "
                f"{_delta(cur['models'][model_id]['calls'], base['models'][model_id]['calls'])} |")
        lines.append("")

        # Per-workflow delta matrix. The effect is TASK-SHAPED: run #110 measured
        # luna at -3.8 OVR on the flagship and +18.6 on high-board for the same
        # effort change, so a single mean hides a sign flip.
        wfs = [w for w in base["workflows"] if w in cur["workflows"]]
        for metric, label in (("ovr", "ΔOVR"), ("obj", "Δobjective"),
                              ("calls", "Δtool calls")):
            lines.append(f"### {label} by workflow")
            lines.append("")
            lines.append("| Model | " + " | ".join(
                WORKFLOW_SHORT.get(w, w) for w in wfs) + " |")
            lines.append("|---|" + ":---:|" * len(wfs))
            for model_id in shared:
                name = get_model(model_id).display_name
                cells = []
                for w in wfs:
                    c = cur["per_wf"].get((model_id, w)) or {}
                    b = base["per_wf"].get((model_id, w)) or {}
                    cells.append(_delta(c.get(metric), b.get(metric)))
                lines.append(f"| {name} | " + " | ".join(cells) + " |")
            lines.append("")

        return "\n".join(lines)
    finally:
        session.close()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--run-id", type=int, required=True)
    ap.add_argument("--out", required=True, help="Path stem, no extension")
    ap.add_argument(
        "--baseline-run", type=int, default=None, metavar="RUN_ID",
        help="Emit a PAIRED comparison instead of a single board: every model "
             "appears as its baseline arm, its --run-id arm, and the delta "
             "between them. Use for an A/B on one variable (effort, output "
             "budget) where each model is its own control. Writes "
             "<out>.compare.md alongside the usual tables.",
    )
    args = ap.parse_args()

    if args.baseline_run is not None:
        text = build_compare(args.run_id, args.baseline_run)
        out = Path(args.out).with_suffix(".compare.md")
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text + "\n")
        print(text)
        print(f"\nwrote {out}")
        return 0

    tables, charts = build(args.run_id)
    stem = Path(args.out)
    stem.parent.mkdir(parents=True, exist_ok=True)
    (stem.with_suffix(".tables.md")).write_text(tables + "\n")
    (stem.with_suffix(".charts.json")).write_text(json.dumps(charts, indent=2) + "\n")
    print(tables)
    print(f"\nwrote {stem.with_suffix('.tables.md')} and {stem.with_suffix('.charts.json')}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
