#!/usr/bin/env python3
"""Refresh `config/model_pricing.json` from ZenMux's public model list.

The arena prices every match from token counts × the gateway's LIST prices. The
list lives in a vendored snapshot, never a runtime fetch, for the same reason as
`config/model_reasoning.json`: a price that silently changes under a board would
re-cost it. Each match records the snapshot it was priced with (`fetched_at` +
`sha256`), so a refresh re-prices only the matches run after it.

A list price is an ESTIMATE. The billed amount per call comes from the gateway's
billing API, keyed by the generation id each call now records
(`scripts/arena_cost_report.py --billed`).

Only USD per-million-token rates are kept (`prompt`, `completion`,
`input_cache_read`, `input_cache_write`). A rate's `conditions.prompt_tokens.gte`
(in kTokens) becomes `min_prompt_ktok`: a request whose prompt reaches it is billed
at that tier, e.g. gpt-6-luna doubles at 272k. Entries with NO condition but
different values (deepseek-v4.1-flash lists 0.075 and 0.15 side by side — a
discount window the list does not describe) are kept as they are; the arena then
reports that model's cost as a low–high range rather than guessing.

Usage:
    python scripts/refresh_model_pricing.py           # write the snapshot
    python scripts/refresh_model_pricing.py --check   # fail if stale
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import urllib.request
from datetime import date
from pathlib import Path

SOURCE_URL = "https://zenmux.ai/api/v1/models"
REPO_ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = REPO_ROOT / "config" / "model_pricing.json"
RATE_KINDS = ("prompt", "completion", "input_cache_read", "input_cache_write")


def _fetch(url: str) -> tuple[dict, str]:
    request = urllib.request.Request(
        url, headers={"User-Agent": "open-otc-trading/model-pricing-refresh"}
    )
    with urllib.request.urlopen(request, timeout=60) as resp:  # noqa: S310 (fixed https URL)
        raw = resp.read()
    return json.loads(raw), hashlib.sha256(raw).hexdigest()


def _tiers(entries: list | None) -> list[dict]:
    out = []
    for e in entries or []:
        if not isinstance(e, dict):
            continue
        if e.get("unit") != "perMTokens" or e.get("currency") != "USD":
            continue
        gte = ((e.get("conditions") or {}).get("prompt_tokens") or {})
        if gte and gte.get("unit") != "kTokens":
            continue  # a condition we cannot evaluate — refuse to guess
        out.append({"usd_per_mtok": float(e["value"]),
                    "min_prompt_ktok": float(gte.get("gte") or 0)})
    return out


def build(payload: dict, sha: str) -> dict:
    models: dict[str, dict] = {}
    for m in payload.get("data") or []:
        pricings = m.get("pricings")
        if not isinstance(pricings, dict):
            continue
        rates = {k: _tiers(pricings.get(k)) for k in RATE_KINDS}
        rates = {k: v for k, v in rates.items() if v}
        if "prompt" in rates and "completion" in rates:
            models[m["id"]] = rates
    return {
        "source": SOURCE_URL,
        "source_sha256": sha,
        "fetched_at": date.today().isoformat(),
        "note": "List prices, USD per 1M tokens. Generated by "
                "scripts/refresh_model_pricing.py; do not hand-edit.",
        "models": dict(sorted(models.items())),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="Exit 1 if the snapshot's prices differ from upstream.")
    args = ap.parse_args()
    payload, sha = _fetch(SOURCE_URL)
    candidate = build(payload, sha)
    if args.check:
        current = json.loads(SNAPSHOT.read_text()) if SNAPSHOT.exists() else {}
        if current.get("models") != candidate["models"]:
            print("config/model_pricing.json is stale — run the refresh.", file=sys.stderr)
            return 1
        return 0
    SNAPSHOT.write_text(json.dumps(candidate, indent=2) + "\n")
    print(f"wrote {SNAPSHOT.relative_to(REPO_ROOT)}: {len(candidate['models'])} models")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
